### ISSUE TITLE
Error in training the tree-structured prediction model

### ISSUE THREAD

**Issue by bsuprith** [orybkin/video-gcp#3]
Hi @orybkin and @kpertsch ,

I get this error while training the tree-structured prediction model on the 25-room navigation dataset: 'AttributeError: Can't pickle local object 'define_layout.<locals>.coords2ridx''. I'm unable to figure out where the pickling is being done to cause this error. Would appreciate your help!

**Comment by orybkin** [comment]
Hi Suprith,

We didn't have this error. I am also not sure about what could cause it, but maybe @kpertsch would know. Does it only happen on the 25-room environment? If you didn't change the code, I believe pickling should only be used for data loading, in which case you could test whether a different dataset or a fake dataset works (I should have a random dataset somewhere that just generates white noise images). This could also happen if you have a custom job scheduler that you added to the code. If you showed the full stack trace it might be easier to figure out.

Oleg

**Comment by bsuprith** [comment]
Thank you for the response, Oleg! I get the same error with the 9-room environment. Here's the full stack trace:

![vgcp_err](https://user-images.githubusercontent.com/54605289/88861023-ae847b80-d1c2-11ea-8770-f428376ffcf0.PNG)

**Comment by kpertsch** [comment]
Hi Suprith,

I haven't seen this error before either. We also don't use pickling in the data loading (our datasets are HDF5-based). From the error stack my best guess would be that the multiprocessing the pytorch dataloader does under the hood uses pickling to pass data loader objects to the individual processes. The particular error you get indicates that it fails to pickle a function handle that is used inside the data loader for rendering the training images (we only store coordinates in the dataset file and render the corresponding images on the fly).

As mentioned, I haven't seen this error, but I successfully used both 9- and 25-room environments with multiple data loading processes. To debug this further you could try two things: 

1. run data loading with a single worker only so that no subprocesses need to be created (to figure out whether the multiprocessing is the issue): just overwrite the `n_workers` variable to be 1 (it is defined around here: https://github.com/orybkin/video-gcp/blob/master/gcp/datasets/data_loader.py#L45)
2. remove the line that renders the images and replace it with outputting a random array of appropriate size (to see whether the rendering is an issue or subprocess creation): the rendering happens here: https://github.com/orybkin/video-gcp/blob/master/gcp/datasets/data_loader.py#L315

Best,
Karl

**Comment by orybkin** [comment]
Seconding Karl, this seems like a strange multi-processing issue. Perhaps you have a different version of python or pytorch.

**Comment by orybkin** [comment]
Please feel free to reopen this if the issue persists.
